version: 5.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

image: Visual Studio 2017

environment:
  docspush_access_token:
    secure: 6t7PwcuHrKWC8CH0N44cg2HQNS+0phTlVFFoD3Cs0nwH/3Hmiblqucs1XR1B7wec

skip_commits:
  files:
    - 'docs\**'

install:
  - git config core.safecrlf false
  - git config core.autocrlf input

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

build_script:
  - ps: .\Build-Docs.ps1
  - ps: .\BuildAll.ps1

test_script:
  - ps: .\Invoke-UnitTests.ps1

artifacts:
  - path: .\BuildOutput\Nuget\LLvm.NET.*.nupkg
  - path: .\BuildOutput\Nuget\LibLLVM.NET.*.nupkg

on_success:
  - ps: .\Push-Docs.ps1
